#!/usr/bin/env python3
"""Refresh the offline lesson catalog and its no-JavaScript HTML fallback."""
import html
import json
import re
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

class LessonParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.title = ''
        self.description = ''
        self.sections = []
        self.heading = None
        self.section_id = ''
        self.quiz = False
        self.bank = False
        self.bank_text = ''
        self.questions = 0

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == 'meta' and attrs.get('name') == 'description':
            self.description = attrs.get('content', '')
        if tag == 'section':
            self.section_id = attrs.get('id', '')
        if tag in ('h1', 'h2'):
            self.heading = [tag, attrs.get('id', self.section_id), '']
        if tag == 'script' and attrs.get('type') == 'application/json' and attrs.get('id', '').startswith('quiz'):
            self.bank = True
            self.bank_text = ''
        if 'data-quiz' in attrs:
            self.quiz = True

    def handle_data(self, data):
        if self.heading is not None:
            self.heading[2] += data
        if self.bank:
            self.bank_text += data

    def handle_endtag(self, tag):
        if self.heading and tag == self.heading[0]:
            text = ' '.join(self.heading[2].split())
            if tag == 'h1':
                self.title = text
            elif self.heading[1]:
                self.sections.append({'id': self.heading[1], 'title': text})
            self.heading = None
        if tag == 'script' and self.bank:
            self.questions += len(json.loads(self.bank_text))
            self.bank = False


def build():
    lessons = []
    for prefix, subject in [('physics', 'Physics'), ('biochem', 'Biochemistry'), ('biology', 'Biology')]:
        for path in sorted((ROOT / 'pages').glob(prefix + '-*.html')):
            parser = LessonParser()
            parser.feed(path.read_text())
            number = re.search(r'-(\d\d)-', path.name)
            lessons.append({'id': path.stem, 'href': 'pages/' + path.name, 'title': parser.title,
                'description': parser.description, 'subject': subject, 'number': number[1] if number else None,
                'questions': parser.questions, 'sections': parser.sections})
    (ROOT / 'assets/js/catalog.js').write_text('// Generated by scripts/build_catalog.py; edit lesson HTML, then regenerate.\nwindow.POSTMED_LESSONS = ' + json.dumps(lessons, ensure_ascii=False, indent=2) + ';\n')
    rows = []
    for lesson in lessons:
        e = html.escape
        label = 'Lesson ' + lesson['number'] if lesson['number'] else 'Companion guide'
        rows.append(f'<article class="lesson-row" data-lesson="{e(lesson["id"])}"><div class="lesson-subject">{e(lesson["subject"])}<span>{label}</span></div><div><h3><a href="{e(lesson["href"])}">{e(lesson["title"])}</a></h3><p>{e(lesson["description"])}</p></div></article>')
    index = ROOT / 'index.html'
    content = re.sub(r'<!-- catalog:start -->.*?<!-- catalog:end -->', '<!-- catalog:start -->\n' + '\n'.join(rows) + '\n<!-- catalog:end -->', index.read_text(), flags=re.S)
    index.write_text(content)
    print(f'Generated {len(lessons)} entries with {sum(x["questions"] for x in lessons)} questions.')

if __name__ == '__main__':
    build()
